Repository Figci/Figci-Client, pull requests merged in 2024-02, with the labels that each got.

#19 Chore: 패키지 설치 및 보일러 플레이트 작성
  .eslintignore
  .eslintrc.cjs
  .gitignore
  .husky/pre-commit
  .prettierrc.json
  README.md
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: enhancement, D-0

#21 Feature: 글로벌 상태 관리 및 라우터 설정
  src/App.jsx
  src/components/App.jsx
  src/components/DiffingResult/index.jsx
  src/components/NewProject/index.jsx
  src/components/Onboarding/index.jsx
  src/components/ProjectPage/index.jsx
  src/components/ProjectVersion/index.jsx
  src/components/shared/Loading.jsx
  src/main.jsx
  store/projectVersion.js
Labels: D-0

#22 Feature: 온보딩 화면 구현
  assets/logo_figci.jpg
  assets/onboarding.png
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/Onboarding/index.jsx
  src/components/shared/Button.jsx
Labels: D-1

#28 Feat: 페이지 별 입력 값 zustand 상태 업데이트 로직 및 공통 컴포넌트 적용
  .eslintrc.cjs
  src/components/NewProject/index.jsx
  src/components/Onboarding/index.jsx
  src/components/ProjectPage/index.jsx
  src/components/ProjectVersion/index.jsx
  src/components/shared/BottomNavigator.jsx
  src/components/shared/Select.jsx
  src/components/shared/Title.jsx
  src/components/utils/generateURI.js
  src/components/utils/getProjectKeyFromURI.js
  src/services/pages.js
  src/services/versions.js
  store/projectAuth.js
  store/projectInit.js
  store/projectPage.js
  store/projectVersion.js
Labels: ASAP

#37 🚑️ [Fix] 그룹 렌더링시 버튼 인스턴스 렌더 되지 않는 버그
  services/createFabricObjects.js
  services/renderFabricFrame.js
  src/components/DiffingResult/index.jsx
Labels: ASAP

#42 Fix: 이미지가 포함된 프레임 리렌더링 전 이미지 안보이는 버그 수정
  src/components/DiffingResult/index.jsx
Labels: ASAP

#45 Fix: 어플리케이션 실행시 toast가 뜨는 버그 수정
  src/components/Onboarding/index.jsx
Labels: bug
